name: Sign image (Legacy)

on:
  workflow_dispatch:
    inputs:
      IMAGE_URL:
        description: 'URL of the image you want to sign. Leave blank to use the image in your repo'
        required: false
        default: ''
jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
 
      - name: Get image
        run: |
          if [ -z "${{ inputs.IMAGE_URL }}" ]; then cp image.img ./aik/1.img else wget "${{ inputs.IMAGE_URL }}" -O ./aik/1.img; fi

      - name: Remove invalid content in your image
        run: |
          ../legacy/header.sh 1.img
          ./unpackimg.sh 1.img
          ./repackimg.sh
          cp -v image-new.img ../legacy/out.img
        working-directory: aik
        
      - name: Sign the image
        run: |
          ./imgheaderinsert out.img 0
          ./sprd_sign out-sign.img config
        working-directory: legacy

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Signed image
          path: 'legacy/out-sign.img'
